"""test1

Revision ID: 42aea204951d
Revises: 
Create Date: 2019-12-16 16:18:28.443115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42aea204951d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent', sa.Column('test', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'parent', ['test'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent', type_='unique')
    op.drop_column('parent', 'test')
    # ### end Alembic commands ###
